apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: component-5o03psulzrt9h
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: component-5o03psulzrt9h
    app.kubernetes.io/part-of: test-gitlabrenovate-9igxfi36aa9cc
  name: component-5o03psulzrt9h
spec:
  ports:
  - name: http-8081
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: go-app
    app.kubernetes.io/instance: component-5o03psulzrt9h
status:
  loadBalancer: {}
